### ISSUE TITLE
canvas.getContext expects incorrect contextType

### ISSUE THREAD

**Issue by Sacharified** [kbirk/webgl-mock#1]
https://github.com/kbirk/webgl-mock/blob/master/src/HTMLCanvasElement.js#L18
It should take `experimental-webgl` as the `contextType` argument, instead of `webgl-experimental`.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext

**Comment by kbirk** [comment]
Thanks for the PR!
